# Generated by Django 5.0.6 on 2024-06-14 07:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplpecom', '0002_customer_product_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Availability',
            new_name='availability',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
